using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Customers
{
    class DataSource
    {
        public static List<Customer> Customers = new List<Customer>{
                new Customer { CustomerID = 1, Title = "Mr", FirstName = "Orlando", LastName = "Gee", EmailAddress = "orlando0@adventure-works.com", Phone = "245-555-0173"},
                new Customer { CustomerID = 2, Title = "Mr", FirstName = "Keith", LastName = "Harris", EmailAddress = "keith0@adventure-works.com", Phone = "170-555-0127"},
                new Customer { CustomerID = 3, Title = "Ms", FirstName = "Donna", LastName = "Carreras", EmailAddress = "donna0@adventure-works.com", Phone = "279-555-0130"},
                new Customer { CustomerID = 4, Title = "Ms", FirstName = "Janet", LastName = "Gates", EmailAddress = "janet1@adventure-works.com", Phone = "710-555-0173"},
                new Customer { CustomerID = 5, Title = "Mr", FirstName = "Lucy", LastName = "Harrington", EmailAddress = "lucy0@adventure-works.com", Phone = "828-555-0186"},
                new Customer { CustomerID = 6, Title = "Ms", FirstName = "Rosmarie", LastName = "Carroll", EmailAddress = "rosmarie0@adventure-works.com", Phone = "244-555-0112"},
                new Customer { CustomerID = 7, Title = "Mr", FirstName = "Dominic", LastName = "Gash", EmailAddress = "dominic0@adventure-works.com", Phone = "192-555-0173"},
                new Customer { CustomerID = 10, Title = "Ms", FirstName = "Kathleen", LastName = "Garza", EmailAddress = "kathleen0@adventure-works.com", Phone = "150-555-0127"},
                new Customer { CustomerID = 11, Title = "Ms", FirstName = "Katherine", LastName = "Harding", EmailAddress = "katherine0@adventure-works.com", Phone = "926-555-0159"},
                new Customer { CustomerID = 12, Title = "Mr", FirstName = "Johnny", LastName = "Caprio", EmailAddress = "johnny0@adventure-works.com", Phone = "112-555-0191"},
                new Customer { CustomerID = 16, Title = "Mr", FirstName = "Christopher", LastName = "Beck", EmailAddress = "christopher1@adventure-works.com", Phone = "1 (11) 500 555-0132"},
                new Customer { CustomerID = 18, Title = "Mr", FirstName = "David", LastName = "Liu", EmailAddress = "david20@adventure-works.com", Phone = "440-555-0132"},
                new Customer { CustomerID = 19, Title = "Mr", FirstName = "John", LastName = "Beaver", EmailAddress = "john8@adventure-works.com", Phone = "521-555-0195"},
                new Customer { CustomerID = 20, Title = "Ms", FirstName = "Jean", LastName = "Handley", EmailAddress = "jean1@adventure-works.com", Phone = "582-555-0113"},
                new Customer { CustomerID = 22, Title = "Ms", FirstName = "Linda", LastName = "Burnett", EmailAddress = "linda4@adventure-works.com", Phone = "121-555-0121"},
                new Customer { CustomerID = 23, Title = "Mr", FirstName = "Kerim", LastName = "Hanif", EmailAddress = "kerim0@adventure-works.com", Phone = "216-555-0122"},
                new Customer { CustomerID = 24, Title = "Mr", FirstName = "Kevin", LastName = "Liu", EmailAddress = "kevin5@adventure-works.com", Phone = "926-555-0164"},
                new Customer { CustomerID = 25, Title = "Mr", FirstName = "Donald", LastName = "Blanton", EmailAddress = "donald0@adventure-works.com", Phone = "357-555-0161"},
                new Customer { CustomerID = 28, Title = "Ms", FirstName = "Jackie", LastName = "Blackwell", EmailAddress = "jackie0@adventure-works.com", Phone = "972-555-0163"},
                new Customer { CustomerID = 29, Title = "Mr", FirstName = "Bryan", LastName = "Hamilton", EmailAddress = "bryan2@adventure-works.com", Phone = "344-555-0144"},
                new Customer { CustomerID = 30, Title = "Mr", FirstName = "Todd", LastName = "Logan", EmailAddress = "todd0@adventure-works.com", Phone = "783-555-0110"},
                new Customer { CustomerID = 34, Title = "Ms", FirstName = "Barbara", LastName = "German", EmailAddress = "barbara4@adventure-works.com", Phone = "1 (11) 500 555-0181"},
                new Customer { CustomerID = 37, Title = "Mr", FirstName = "Jim", LastName = "Geist", EmailAddress = "jim1@adventure-works.com", Phone = ""},
                new Customer { CustomerID = 38, Title = "Ms", FirstName = "Betty", LastName = "Haines", EmailAddress = "betty0@adventure-works.com", Phone = "867-555-0114"},
                new Customer { CustomerID = 39, Title = "Ms", FirstName = "Sharon", LastName = "Looney", EmailAddress = "sharon2@adventure-works.com", Phone = "377-555-0132"},
                new Customer { CustomerID = 40, Title = "Mr", FirstName = "Darren", LastName = "Gehring", EmailAddress = "darren0@adventure-works.com", Phone = "417-555-0182"},
                new Customer { CustomerID = 41, Title = "Ms", FirstName = "Erin", LastName = "Hagens", EmailAddress = "erin1@adventure-works.com", Phone = "244-555-0127"},
                new Customer { CustomerID = 42, Title = "Mr", FirstName = "Jeremy", LastName = "Los", EmailAddress = "jeremy0@adventure-works.com", Phone = "911-555-0165"},
                new Customer { CustomerID = 43, Title = "Ms", FirstName = "Elsa", LastName = "Leavitt", EmailAddress = "elsa0@adventure-works.com", Phone = "482-555-0174"},
                new Customer { CustomerID = 46, Title = "Mr", FirstName = "David", LastName = "Lawrence", EmailAddress = "david19@adventure-works.com", Phone = "653-555-0159"},
                new Customer { CustomerID = 47, Title = "Ms", FirstName = "Hattie", LastName = "Haemon", EmailAddress = "hattie0@adventure-works.com", Phone = "141-555-0172"},
                new Customer { CustomerID = 48, Title = "Ms", FirstName = "Anita", LastName = "Lucerne", EmailAddress = "anita0@adventure-works.com", Phone = "164-555-0118"},
                new Customer { CustomerID = 52, Title = "Ms", FirstName = "Rebecca", LastName = "Laszlo", EmailAddress = "rebecca2@adventure-works.com", Phone = "1 (11) 500 555-0155"},
                new Customer { CustomerID = 55, Title = "Mr", FirstName = "Eric", LastName = "Lang", EmailAddress = "eric6@adventure-works.com", Phone = "932-555-0163"},
                new Customer { CustomerID = 56, Title = "Mr", FirstName = "Brian", LastName = "Groth", EmailAddress = "brian5@adventure-works.com", Phone = "461-555-0118"},
                new Customer { CustomerID = 57, Title = "Ms", FirstName = "Judy", LastName = "Lundahl", EmailAddress = "judy1@adventure-works.com", Phone = "260-555-0130"},
                new Customer { CustomerID = 58, Title = "Mr", FirstName = "Peter", LastName = "Kurniawan", EmailAddress = "peter4@adventure-works.com", Phone = "436-555-0160"},
                new Customer { CustomerID = 59, Title = "Mr", FirstName = "Douglas", LastName = "Groncki", EmailAddress = "douglas2@adventure-works.com", Phone = "385-555-0140"},
                new Customer { CustomerID = 60, Title = "Mr", FirstName = "Sean", LastName = "Lunt", EmailAddress = "sean4@adventure-works.com", Phone = "183-555-0111"},
                new Customer { CustomerID = 61, Title = "Mr", FirstName = "Jeffrey", LastName = "Kurtz", EmailAddress = "jeffrey3@adventure-works.com", Phone = "452-555-0179"},
                new Customer { CustomerID = 64, Title = "Mr", FirstName = "Vamsi", LastName = "Kuppa", EmailAddress = "vamsi1@adventure-works.com", Phone = "290-555-0196"},
                new Customer { CustomerID = 65, Title = "Ms", FirstName = "Jane", LastName = "Greer", EmailAddress = "jane2@adventure-works.com", Phone = "737-555-0163"},
                new Customer { CustomerID = 66, Title = "Mr", FirstName = "Alexander", LastName = "Deborde", EmailAddress = "alexander1@adventure-works.com", Phone = "394-555-0176"},
                new Customer { CustomerID = 70, Title = "Mr", FirstName = "Deepak", LastName = "Kumar", EmailAddress = "deepak0@adventure-works.com", Phone = "1 (11) 500 555-0122"},
                new Customer { CustomerID = 73, Title = "Ms", FirstName = "Margaret", LastName = "Krupka", EmailAddress = "margaret1@adventure-works.com", Phone = "107-555-0132"},
                new Customer { CustomerID = 74, Title = "Mr", FirstName = "Christopher", LastName = "Bright", EmailAddress = "christopher2@adventure-works.com", Phone = "162-555-0166"},
                new Customer { CustomerID = 75, Title = "Ms", FirstName = "Aidan", LastName = "Delaney", EmailAddress = "aidan0@adventure-works.com", Phone = "358-555-0188"},
                new Customer { CustomerID = 76, Title = "Mr", FirstName = "James", LastName = "Krow", EmailAddress = "james11@adventure-works.com", Phone = "265-555-0190"},
                new Customer { CustomerID = 77, Title = "Mr", FirstName = "Michael", LastName = "Brundage", EmailAddress = "michael13@adventure-works.com", Phone = "128-555-0148"},
                new Customer { CustomerID = 78, Title = "Mr", FirstName = "Stefan", LastName = "Delmarco", EmailAddress = "stefan0@adventure-works.com", Phone = "819-555-0186"},
                new Customer { CustomerID = 79, Title = "Mr", FirstName = "Mitch", LastName = "Kennedy", EmailAddress = "mitch0@adventure-works.com", Phone = "996-555-0192"},
                new Customer { CustomerID = 82, Title = "Mr", FirstName = "James", LastName = "Kramer", EmailAddress = "james10@adventure-works.com", Phone = "814-555-0130"},
                new Customer { CustomerID = 83, Title = "Mr", FirstName = "Eric", LastName = "Brumfield", EmailAddress = "eric3@adventure-works.com", Phone = "644-555-0114"},
                new Customer { CustomerID = 84, Title = "Ms", FirstName = "Della", LastName = "Demott Jr", EmailAddress = "della0@adventure-works.com", Phone = "752-555-0185"},
                new Customer { CustomerID = 88, Title = "Ms", FirstName = "Pamala", LastName = "Kotc", EmailAddress = "pamala0@adventure-works.com", Phone = "1 (11) 500 555-0173"},
                new Customer { CustomerID = 91, Title = "Ms", FirstName = "Joy", LastName = "Koski", EmailAddress = "joy0@adventure-works.com", Phone = "810-555-0198"},
                new Customer { CustomerID = 92, Title = "Ms", FirstName = "Jovita", LastName = "Carmody", EmailAddress = "jovita0@adventure-works.com", Phone = "646-555-0137"},
                new Customer { CustomerID = 93, Title = "Mr", FirstName = "Prashanth", LastName = "Desai", EmailAddress = "prashanth0@adventure-works.com", Phone = "138-555-0156"},
                new Customer { CustomerID = 94, Title = "Mr", FirstName = "Scott", LastName = "Konersmann", EmailAddress = "scott6@adventure-works.com", Phone = "556-555-0192"},
                new Customer { CustomerID = 95, Title = "Ms", FirstName = "Jane", LastName = "Carmichael", EmailAddress = "jane0@adventure-works.com", Phone = "716-555-0167"},
                new Customer { CustomerID = 96, Title = "Ms", FirstName = "Bonnie", LastName = "Lepro", EmailAddress = "bonnie2@adventure-works.com", Phone = "354-555-0130"},
                new Customer { CustomerID = 97, Title = "Mr", FirstName = "Eugene", LastName = "Kogan", EmailAddress = "eugene2@adventure-works.com", Phone = "136-555-0134"},
                new Customer { CustomerID = 100, Title = "Mr", FirstName = "Kirk", LastName = "King", EmailAddress = "kirk2@adventure-works.com", Phone = "979-555-0163"},
                new Customer { CustomerID = 101, Title = "Mr", FirstName = "William", LastName = "Conner", EmailAddress = "william1@adventure-works.com", Phone = "383-555-0111"},
                new Customer { CustomerID = 102, Title = "Ms", FirstName = "Linda", LastName = "Leste", EmailAddress = "linda7@adventure-works.com", Phone = "493-555-0134"},
                new Customer { CustomerID = 106, Title = "Ms", FirstName = "Andrea", LastName = "Thomsen", EmailAddress = "andrea1@adventure-works.com", Phone = "1 (11) 500 555-0120"},
                new Customer { CustomerID = 109, Title = "Mr", FirstName = "Daniel", LastName = "Thompson", EmailAddress = "daniel2@adventure-works.com", Phone = "247-555-0197"},
                new Customer { CustomerID = 110, Title = "Ms", FirstName = "Kendra", LastName = "Thompson", EmailAddress = "kendra0@adventure-works.com", Phone = "464-555-0188"},
                new Customer { CustomerID = 111, Title = "Mr", FirstName = "Scott", LastName = "Colvin", EmailAddress = "scott1@adventure-works.com", Phone = "119-555-0144"},
                new Customer { CustomerID = 112, Title = "Ms", FirstName = "Elsie", LastName = "Lewin", EmailAddress = "elsie0@adventure-works.com", Phone = "803-555-0116"},
                new Customer { CustomerID = 113, Title = "Mr", FirstName = "Donald", LastName = "Thompson", EmailAddress = "donald1@adventure-works.com", Phone = "273-555-0111"},
                new Customer { CustomerID = 114, Title = "Mr", FirstName = "John", LastName = "Colon", EmailAddress = "john14@adventure-works.com", Phone = "397-555-0144"},
                new Customer { CustomerID = 115, Title = "Mr", FirstName = "George", LastName = "Li", EmailAddress = "george3@adventure-works.com", Phone = "699-555-0183"},
                new Customer { CustomerID = 118, Title = "Mr", FirstName = "Yale", LastName = "Li", EmailAddress = "yale0@adventure-works.com", Phone = "316-555-0138"},
                new Customer { CustomerID = 119, Title = "Ms", FirstName = "Phyllis", LastName = "Thomas", EmailAddress = "phyllis2@adventure-works.com", Phone = "667-555-0112"},
                new Customer { CustomerID = 120, Title = "Mr", FirstName = "Pat", LastName = "Coleman", EmailAddress = "pat2@adventure-works.com", Phone = "292-555-0128"},
                new Customer { CustomerID = 124, Title = "Ms", FirstName = "Yuhong", LastName = "Li", EmailAddress = "yuhong1@adventure-works.com", Phone = "1 (11) 500 555-0176"},
                new Customer { CustomerID = 127, Title = "Mr", FirstName = "Joseph", LastName = "Lique", EmailAddress = "joseph2@adventure-works.com", Phone = "119-555-0195"},
                new Customer { CustomerID = 128, Title = "Ms", FirstName = "Judy", LastName = "Thames", EmailAddress = "judy3@adventure-works.com", Phone = "799-555-0118"},
                new Customer { CustomerID = 129, Title = "Ms", FirstName = "Connie", LastName = "Coffman", EmailAddress = "connie0@adventure-works.com", Phone = "426-555-0181"},
                new Customer { CustomerID = 130, Title = "Mr", FirstName = "Paulo", LastName = "Lisboa", EmailAddress = "paulo0@adventure-works.com", Phone = "380-555-0116"},
                new Customer { CustomerID = 131, Title = "Ms", FirstName = "Vanessa", LastName = "Tench", EmailAddress = "vanessa0@adventure-works.com", Phone = "785-555-0163"},
                new Customer { CustomerID = 132, Title = "Ms", FirstName = "Teanna", LastName = "Cobb", EmailAddress = "teanna0@adventure-works.com", Phone = "661-555-0168"},
                new Customer { CustomerID = 133, Title = "Mr", FirstName = "Michael", LastName = "Graff", EmailAddress = "michael16@adventure-works.com", Phone = "132-555-0150"},
                new Customer { CustomerID = 136, Title = "Mr", FirstName = "Derek", LastName = "Graham", EmailAddress = "derek0@adventure-works.com", Phone = "674-555-0187"},
                new Customer { CustomerID = 138, Title = "Ms", FirstName = "Jane", LastName = "Clayton", EmailAddress = "jane1@adventure-works.com", Phone = "206-555-0195"},
                new Customer { CustomerID = 142, Title = "Mr", FirstName = "Jon", LastName = "Grande", EmailAddress = "jon1@adventure-works.com", Phone = "1 (11) 500 555-0114"},
                new Customer { CustomerID = 145, Title = "Mr", FirstName = "Ted", LastName = "Bremer", EmailAddress = "ted0@adventure-works.com", Phone = "962-555-0166"},
                new Customer { CustomerID = 146, Title = "Mr", FirstName = "Richard", LastName = "Bready", EmailAddress = "richard1@adventure-works.com", Phone = "340-555-0131"},
                new Customer { CustomerID = 147, Title = "Ms", FirstName = "Alice", LastName = "Clark", EmailAddress = "alice1@adventure-works.com", Phone = "221-555-0141"},
                new Customer { CustomerID = 148, Title = "Mr", FirstName = "Alan", LastName = "Brewer", EmailAddress = "alan1@adventure-works.com", Phone = "494-555-0134"},
                new Customer { CustomerID = 149, Title = "Mr", FirstName = "Cornelius", LastName = "Brandon", EmailAddress = "cornelius0@adventure-works.com", Phone = "229-555-0114"},
                new Customer { CustomerID = 150, Title = "Ms", FirstName = "Jill", LastName = "Christie", EmailAddress = "jill1@adventure-works.com", Phone = "927-555-0198"},
                new Customer { CustomerID = 151, Title = "Mr", FirstName = "Walter", LastName = "Brian", EmailAddress = "walter0@adventure-works.com", Phone = "163-555-0155"},
                new Customer { CustomerID = 154, Title = "Mr", FirstName = "Carlton", LastName = "Carlisle", EmailAddress = "carlton0@adventure-works.com", Phone = "193-555-0116"},
                new Customer { CustomerID = 155, Title = "Mr", FirstName = "Joseph", LastName = "Castellucio", EmailAddress = "joseph1@adventure-works.com", Phone = "180-555-0114"},
                new Customer { CustomerID = 156, Title = "Mr", FirstName = "Lester", LastName = "Bowman", EmailAddress = "lester0@adventure-works.com", Phone = "844-555-0112"},
                new Customer { CustomerID = 160, Title = "Ms", FirstName = "Brigid", LastName = "Cavendish", EmailAddress = "brigid0@adventure-works.com", Phone = "1 (11) 500 555-0178"},
                new Customer { CustomerID = 163, Title = "Mr", FirstName = "Andrew", LastName = "Cencini", EmailAddress = "andrew2@adventure-works.com", Phone = "644-555-0111"},
                new Customer { CustomerID = 164, Title = "Ms", FirstName = "Cindy", LastName = "Dodd", EmailAddress = "cindy0@adventure-works.com", Phone = "706-555-0140"},
                new Customer { CustomerID = 165, Title = "Mr", FirstName = "Randall", LastName = "Boseman", EmailAddress = "randall0@adventure-works.com", Phone = "383-555-0117"},
                new Customer { CustomerID = 166, Title = "Ms", FirstName = "Stacey", LastName = "Cereghino", EmailAddress = "stacey0@adventure-works.com", Phone = "351-555-0131"},
                new Customer { CustomerID = 167, Title = "Mr", FirstName = "Blaine", LastName = "Dockter", EmailAddress = "blaine0@adventure-works.com", Phone = "156-555-0187"},
                new Customer { CustomerID = 168, Title = "Mr", FirstName = "Luis", LastName = "Bonifaz", EmailAddress = "luis0@adventure-works.com", Phone = "688-555-0113"},
                new Customer { CustomerID = 169, Title = "Ms", FirstName = "Brenda", LastName = "Diaz", EmailAddress = "brenda2@adventure-works.com", Phone = "147-555-0192"},
                new Customer { CustomerID = 172, Title = "Ms", FirstName = "Gabriele", LastName = "Dickmann", EmailAddress = "gabriele0@adventure-works.com", Phone = "835-555-0116"},
                new Customer { CustomerID = 173, Title = "Mr", FirstName = "Rudolph", LastName = "Dillon", EmailAddress = "rudolph0@adventure-works.com", Phone = "722-555-0169"},
                new Customer { CustomerID = 174, Title = "Mr", FirstName = "Michael", LastName = "Bohling", EmailAddress = "michael12@adventure-works.com", Phone = "838-555-0147"},
                new Customer { CustomerID = 178, Title = "Mr", FirstName = "Dick", LastName = "Dievendorff", EmailAddress = "dick1@adventure-works.com", Phone = "1 (11) 500 555-0193"},
                new Customer { CustomerID = 180, Title = "Ms", FirstName = "Nicky", LastName = "Chesnut", EmailAddress = "nicky0@adventure-works.com", Phone = "264-555-0164"},
                new Customer { CustomerID = 181, Title = "Mr", FirstName = "Michael", LastName = "Lee", EmailAddress = "michael18@adventure-works.com", Phone = "396-555-0139"},
                new Customer { CustomerID = 182, Title = "Mr", FirstName = "Stanley", LastName = "Alan", EmailAddress = "stanley0@adventure-works.com", Phone = "156-555-0126"},
                new Customer { CustomerID = 183, Title = "Mr", FirstName = "Yao-Qiang", LastName = "Cheng", EmailAddress = "yao-qiang0@adventure-works.com", Phone = "344-555-0181"},
                new Customer { CustomerID = 184, Title = "Ms", FirstName = "Marjorie", LastName = "Lee", EmailAddress = "marjorie0@adventure-works.com", Phone = "306-555-0166"},
                new Customer { CustomerID = 185, Title = "Mr", FirstName = "Sandeep", LastName = "Kaliyath", EmailAddress = "sandeep1@adventure-works.com", Phone = "495-555-0113"},
                new Customer { CustomerID = 186, Title = "Mr", FirstName = "Pei", LastName = "Chow", EmailAddress = "pei0@adventure-works.com", Phone = "789-555-0184"},
                new Customer { CustomerID = 187, Title = "Mr", FirstName = "Frank", LastName = "Campbell", EmailAddress = "frank4@adventure-works.com", Phone = "491-555-0132"},
                new Customer { CustomerID = 190, Title = "Mr", FirstName = "Mark", LastName = "Lee", EmailAddress = "mark5@adventure-works.com", Phone = "371-555-0112"},
                new Customer { CustomerID = 191, Title = "Ms", FirstName = "Sandra", LastName = "Kitt", EmailAddress = "sandra2@adventure-works.com", Phone = "303-555-0117"},
                new Customer { CustomerID = 192, Title = "Mr", FirstName = "Hao", LastName = "Chen", EmailAddress = "hao1@adventure-works.com", Phone = "117-555-0173"},
                new Customer { CustomerID = 196, Title = "Ms", FirstName = "Jolie", LastName = "Lenehan", EmailAddress = "jolie0@adventure-works.com", Phone = "1 (11) 500 555-0126"},
                new Customer { CustomerID = 197, Title = "Ms", FirstName = "Diane", LastName = "Krane", EmailAddress = "diane4@adventure-works.com", Phone = "224-555-0126"},
                new Customer { CustomerID = 198, Title = "Mr", FirstName = "Payton", LastName = "Benson", EmailAddress = "payton0@adventure-works.com", Phone = "528-555-0183"},
                new Customer { CustomerID = 199, Title = "Mr", FirstName = "Roger", LastName = "Lengel", EmailAddress = "roger1@adventure-works.com", Phone = "947-555-0143"},
                new Customer { CustomerID = 200, Title = "Ms", FirstName = "Peggy", LastName = "Justice", EmailAddress = "peggy0@adventure-works.com", Phone = "170-555-0189"},
                new Customer { CustomerID = 201, Title = "Ms", FirstName = "Edna", LastName = "Benson", EmailAddress = "edna0@adventure-works.com", Phone = "789-555-0189"},
                new Customer { CustomerID = 203, Title = "Ms", FirstName = "Jean", LastName = "Jordan", EmailAddress = "jean3@adventure-works.com", Phone = "207-555-0129"},
                new Customer { CustomerID = 204, Title = "Mr", FirstName = "Ido", LastName = "Ben-Sachar", EmailAddress = "ido0@adventure-works.com", Phone = "973-555-0112"},
                new Customer { CustomerID = 205, Title = "Mr", FirstName = "Frank", LastName = "Mart¡nez", EmailAddress = "frank5@adventure-works.com", Phone = "171-555-0147"},
                new Customer { CustomerID = 208, Title = "Mr", FirstName = "Steve", LastName = "Masters", EmailAddress = "steve2@adventure-works.com", Phone = "154-555-0115"},
                new Customer { CustomerID = 209, Title = "Mr", FirstName = "Robert", LastName = "Jones", EmailAddress = "robert6@adventure-works.com", Phone = "595-555-0131"},
                new Customer { CustomerID = 210, Title = "Mr", FirstName = "Josh", LastName = "Barnhill", EmailAddress = "josh0@adventure-works.com", Phone = "584-555-0192"},
                new Customer { CustomerID = 214, Title = "Ms", FirstName = "Jennifer", LastName = "Maxham", EmailAddress = "jennifer1@adventure-works.com", Phone = "1 (11) 500 555-0175"},
                new Customer { CustomerID = 217, Title = "Mr", FirstName = "Chris", LastName = "Maxwell", EmailAddress = "chris6@adventure-works.com", Phone = "642-555-0187"},
                new Customer { CustomerID = 218, Title = "Mr", FirstName = "David", LastName = "Johnson", EmailAddress = "david18@adventure-works.com", Phone = "476-555-0139"},
                new Customer { CustomerID = 219, Title = "Mr", FirstName = "Brian", LastName = "Johnson", EmailAddress = "brian6@adventure-works.com", Phone = "320-555-0134"},
                new Customer { CustomerID = 220, Title = "Mr", FirstName = "Robert", LastName = "Brown", EmailAddress = "robert5@adventure-works.com", Phone = "575-555-0189"},
                new Customer { CustomerID = 221, Title = "Ms", FirstName = "Sandra", LastName = "Maynard", EmailAddress = "sandra4@adventure-works.com", Phone = "993-555-0179"},
                new Customer { CustomerID = 222, Title = "Mr", FirstName = "Barry", LastName = "Johnson", EmailAddress = "barry1@adventure-works.com", Phone = "858-555-0140"},
                new Customer { CustomerID = 223, Title = "Ms", FirstName = "Joyce", LastName = "Jarvis", EmailAddress = "joyce0@adventure-works.com", Phone = "458-555-0179"},
                new Customer { CustomerID = 226, Title = "Ms", FirstName = "Vance", LastName = "Johns", EmailAddress = "vance0@adventure-works.com", Phone = "103-555-0151"},
                new Customer { CustomerID = 227, Title = "Ms", FirstName = "Robin", LastName = "McGuigan", EmailAddress = "robin0@adventure-works.com", Phone = "431-555-0153"},
                new Customer { CustomerID = 228, Title = "Ms", FirstName = "Danielle", LastName = "Johnson", EmailAddress = "danielle1@adventure-works.com", Phone = "356-555-0190"},
                new Customer { CustomerID = 232, Title = "Mr", FirstName = "David", LastName = "Jaffe", EmailAddress = "david17@adventure-works.com", Phone = "1 (11) 500 555-0140"},
                new Customer { CustomerID = 235, Title = "Ms", FirstName = "Mary", LastName = "Alexander", EmailAddress = "mary7@adventure-works.com", Phone = "344-555-0133"},
                new Customer { CustomerID = 236, Title = "Ms", FirstName = "Lola", LastName = "McCarthy", EmailAddress = "lola0@adventure-works.com", Phone = "173-555-0151"},
                new Customer { CustomerID = 237, Title = "Ms", FirstName = "Mary", LastName = "Browning", EmailAddress = "mary5@adventure-works.com", Phone = "658-555-0146"},
                new Customer { CustomerID = 238, Title = "Ms", FirstName = "Jodan", LastName = "Jacobson", EmailAddress = "jodan0@adventure-works.com", Phone = "652-555-0189"},
                new Customer { CustomerID = 239, Title = "Ms", FirstName = "Jane", LastName = "McCarty", EmailAddress = "jane3@adventure-works.com", Phone = "529-555-0195"},
                new Customer { CustomerID = 240, Title = "Mr", FirstName = "Jessie", LastName = "Valerio", EmailAddress = "jessie0@adventure-works.com", Phone = "103-555-0179"},
                new Customer { CustomerID = 241, Title = "Mr", FirstName = "Eric", LastName = "Jacobsen", EmailAddress = "eric5@adventure-works.com", Phone = "703-555-0120"},
                new Customer { CustomerID = 244, Title = "Mr", FirstName = "Bronson", LastName = "Jacobs", EmailAddress = "bronson0@adventure-works.com", Phone = "697-555-0131"},
                new Customer { CustomerID = 245, Title = "Mr", FirstName = "James", LastName = "McCoy", EmailAddress = "james12@adventure-works.com", Phone = "191-555-0151"},
                new Customer { CustomerID = 246, Title = "Ms", FirstName = "Esther", LastName = "Valle", EmailAddress = "esther0@adventure-works.com", Phone = "481-555-0131"},
                new Customer { CustomerID = 250, Title = "Ms", FirstName = "Denean", LastName = "Ison", EmailAddress = "denean0@adventure-works.com", Phone = "1 (11) 500 555-0127"},
                new Customer { CustomerID = 253, Title = "Mr", FirstName = "Erik", LastName = "Ismert", EmailAddress = "erik0@adventure-works.com", Phone = "116-555-0163"},
                new Customer { CustomerID = 254, Title = "Mr", FirstName = "Robert", LastName = "Bernacchi", EmailAddress = "robert4@adventure-works.com", Phone = "449-555-0176"},
                new Customer { CustomerID = 255, Title = "Mr", FirstName = "Sunil", LastName = "Uppal", EmailAddress = "sunil0@adventure-works.com", Phone = "184-555-0187"},
                new Customer { CustomerID = 256, Title = "Mr", FirstName = "Richard", LastName = "Irwin", EmailAddress = "richard4@adventure-works.com", Phone = "367-555-0124"},
                new Customer { CustomerID = 257, Title = "Mr", FirstName = "Matthias", LastName = "Berndt", EmailAddress = "matthias1@adventure-works.com", Phone = "384-555-0169"},
                new Customer { CustomerID = 258, Title = "Mr", FirstName = "Sairaj", LastName = "Uddin", EmailAddress = "sairaj1@adventure-works.com", Phone = "767-555-0193"},
                new Customer { CustomerID = 259, Title = "Mr", FirstName = "Lucio", LastName = "Iallo", EmailAddress = "lucio0@adventure-works.com", Phone = "199-555-0135"},
                new Customer { CustomerID = 262, Title = "Ms", FirstName = "Beth", LastName = "Inghram", EmailAddress = "beth0@adventure-works.com", Phone = "718-555-0152"},
                new Customer { CustomerID = 263, Title = "Mr", FirstName = "Timothy", LastName = "Burnett", EmailAddress = "timothy0@adventure-works.com", Phone = "251-555-0172"},
                new Customer { CustomerID = 264, Title = "Ms", FirstName = "Phyllis", LastName = "Tuffield", EmailAddress = "phyllis3@adventure-works.com", Phone = "277-555-0182"},
                new Customer { CustomerID = 268, Title = "Mr", FirstName = "Richard", LastName = "Byham", EmailAddress = "richard2@adventure-works.com", Phone = "1 (11) 500 555-0138"},
                new Customer { CustomerID = 271, Title = "Mr", FirstName = "Jared", LastName = "Bustamante", EmailAddress = "jared0@adventure-works.com", Phone = "164-555-0147"},
                new Customer { CustomerID = 272, Title = "Mr", FirstName = "Henry", LastName = "Campen", EmailAddress = "henry0@adventure-works.com", Phone = "635-555-0126"},
                new Customer { CustomerID = 273, Title = "Ms", FirstName = "Christie", LastName = "Trujillo", EmailAddress = "christie0@adventure-works.com", Phone = "686-555-0180"},
                new Customer { CustomerID = 274, Title = "Ms", FirstName = "Janet", LastName = "Gilliat", EmailAddress = "janet2@adventure-works.com", Phone = "521-555-0183"},
                new Customer { CustomerID = 275, Title = "Mr", FirstName = "Chris", LastName = "Cannon", EmailAddress = "chris5@adventure-works.com", Phone = "118-555-0131"},
                new Customer { CustomerID = 276, Title = "Mr", FirstName = "Michael John", LastName = "Troyer", EmailAddress = "michaeljohn0@adventure-works.com", Phone = "308-555-0175"},
                new Customer { CustomerID = 277, Title = "Mr", FirstName = "Guy", LastName = "Gilbert", EmailAddress = "guy0@adventure-works.com", Phone = "583-555-0198"},
                new Customer { CustomerID = 280, Title = "Mr", FirstName = "Frances", LastName = "Giglio", EmailAddress = "frances1@adventure-works.com", Phone = "692-555-0136"},
                new Customer { CustomerID = 281, Title = "Ms", FirstName = "Suzana De Abreu", LastName = "Canuto", EmailAddress = "suzanadeabreu0@adventure-works.com", Phone = "990-555-0141"},
                new Customer { CustomerID = 282, Title = "Mr", FirstName = "Billy", LastName = "Trent", EmailAddress = "billy0@adventure-works.com", Phone = "882-555-0115"},
                new Customer { CustomerID = 286, Title = "Mr", FirstName = "Leo", LastName = "Giakoumakis", EmailAddress = "leo0@adventure-works.com", Phone = "1 (11) 500 555-0169"},
                new Customer { CustomerID = 287, Title = "Mr", FirstName = "Grant", LastName = "Culbertson", EmailAddress = "grant1@adventure-works.com", Phone = "859-555-0173"},
                new Customer { CustomerID = 288, Title = "Mr", FirstName = "Robert", LastName = "Barker", EmailAddress = "robert3@adventure-works.com", Phone = "241-555-0112"},
                new Customer { CustomerID = 289, Title = "Ms", FirstName = "Gabriel", LastName = "Bockenkamp", EmailAddress = "gabriel0@adventure-works.com", Phone = "763-555-0145"},
                new Customer { CustomerID = 290, Title = "Mr", FirstName = "Scott", LastName = "Culp", EmailAddress = "scott3@adventure-works.com", Phone = "119-555-0167"},
                new Customer { CustomerID = 291, Title = "Mr", FirstName = "Wayne", LastName = "Banack", EmailAddress = "wayne0@adventure-works.com", Phone = "640-555-0189"},
                new Customer { CustomerID = 292, Title = "Mr", FirstName = "Michael", LastName = "Blythe", EmailAddress = "michael11@adventure-works.com", Phone = "126-555-0172"},
                new Customer { CustomerID = 293, Title = "Mr", FirstName = "Conor", LastName = "Cunningham", EmailAddress = "conor0@adventure-works.com", Phone = "115-555-0113"},
                new Customer { CustomerID = 294, Title = "Mr", FirstName = "Alberto", LastName = "Baltazar", EmailAddress = "alberto0@adventure-works.com", Phone = "780-555-0114"},
                new Customer { CustomerID = 295, Title = "Mr", FirstName = "Joseph", LastName = "Mitzner", EmailAddress = "joseph4@adventure-works.com", Phone = "129-555-0164"},
                new Customer { CustomerID = 298, Title = "Mr", FirstName = "Robert", LastName = "Mitosinka", EmailAddress = "robert10@adventure-works.com", Phone = "239-555-0198"},
                new Customer { CustomerID = 299, Title = "Mr", FirstName = "Thierry", LastName = "D'Hers", EmailAddress = "thierry1@adventure-works.com", Phone = "680-555-0192"},
                new Customer { CustomerID = 300, Title = "Mr", FirstName = "Daniel", LastName = "Blanco", EmailAddress = "daniel0@adventure-works.com", Phone = "221-555-0167"},
                new Customer { CustomerID = 304, Title = "Ms", FirstName = "Linda", LastName = "Mitchell", EmailAddress = "linda9@adventure-works.com", Phone = "1 (11) 500 555-0182"},
                new Customer { CustomerID = 306, Title = "Mr", FirstName = "Stephen", LastName = "Ayers", EmailAddress = "stephen1@adventure-works.com", Phone = "818-555-0171"},
                new Customer { CustomerID = 307, Title = "Ms", FirstName = "Neva", LastName = "Mitchell", EmailAddress = "neva0@adventure-works.com", Phone = "992-555-0134"},
                new Customer { CustomerID = 308, Title = "Ms", FirstName = "Megan", LastName = "Davis", EmailAddress = "megan1@adventure-works.com", Phone = "839-555-0198"},
                new Customer { CustomerID = 309, Title = "Mr", FirstName = "John", LastName = "Arthur", EmailAddress = "john6@adventure-works.com", Phone = "149-555-0113"},
                new Customer { CustomerID = 310, Title = "Mr", FirstName = "Frank", LastName = "Miller", EmailAddress = "frank6@adventure-works.com", Phone = "118-555-0184"},
                new Customer { CustomerID = 311, Title = "Mr", FirstName = "Alvaro", LastName = "De Matos Miranda Filho", EmailAddress = "alvaro0@adventure-works.com", Phone = "551-555-0155"},
                new Customer { CustomerID = 312, Title = "Mr", FirstName = "Thomas", LastName = "Armstrong", EmailAddress = "thomas1@adventure-works.com", Phone = "226-555-0146"},
                new Customer { CustomerID = 313, Title = "Mr", FirstName = "Dylan", LastName = "Miller", EmailAddress = "dylan1@adventure-works.com", Phone = "140-555-0192"},
                new Customer { CustomerID = 316, Title = "Mr", FirstName = "Ben", LastName = "Miller", EmailAddress = "ben1@adventure-works.com", Phone = "207-555-0167"},
                new Customer { CustomerID = 317, Title = "Mr", FirstName = "Jacob", LastName = "Dean", EmailAddress = "jacob0@adventure-works.com", Phone = "767-555-0151"},
                new Customer { CustomerID = 318, Title = "Ms", FirstName = "Ann", LastName = "Beebe", EmailAddress = "ann0@adventure-works.com", Phone = "277-555-0169"},
                new Customer { CustomerID = 322, Title = "Mr", FirstName = "Matthew", LastName = "Miller", EmailAddress = "matthew5@adventure-works.com", Phone = "1 (11) 500 555-0176"},
                new Customer { CustomerID = 323, Title = "Mr", FirstName = "Jo", LastName = "Brown", EmailAddress = "jo2@adventure-works.com", Phone = "689-555-0130"},
                new Customer { CustomerID = 325, Title = "Ms", FirstName = "Virginia", LastName = "Miller", EmailAddress = "virginia0@adventure-works.com", Phone = "918-555-0127"},
                new Customer { CustomerID = 326, Title = "Mr", FirstName = "Scott", LastName = "Gode", EmailAddress = "scott4@adventure-works.com", Phone = "164-555-0145"},
                new Customer { CustomerID = 327, Title = "Ms", FirstName = "Caroline", LastName = "Vicknair", EmailAddress = "caroline0@adventure-works.com", Phone = "695-555-0158"},
                new Customer { CustomerID = 328, Title = "Mr", FirstName = "Robert", LastName = "Vessa", EmailAddress = "robert13@adventure-works.com", Phone = "560-555-0171"},
                new Customer { CustomerID = 330, Title = "Mr", FirstName = "Mete", LastName = "Goktepe", EmailAddress = "mete0@adventure-works.com", Phone = "637-555-0120"},
                new Customer { CustomerID = 331, Title = "Ms", FirstName = "Wanda", LastName = "Vernon", EmailAddress = "wanda0@adventure-works.com", Phone = "433-555-0168"},
                new Customer { CustomerID = 334, Title = "Ms", FirstName = "Dora", LastName = "Verdad", EmailAddress = "dora0@adventure-works.com", Phone = "155-555-0140"},
                new Customer { CustomerID = 335, Title = "Mr", FirstName = "John", LastName = "Berger", EmailAddress = "john10@adventure-works.com", Phone = "156-555-0111"},
                new Customer { CustomerID = 336, Title = "Mr", FirstName = "Brian", LastName = "Goldstein", EmailAddress = "brian4@adventure-works.com", Phone = "495-555-0161"},
                new Customer { CustomerID = 340, Title = "Mr", FirstName = "Raja", LastName = "Venugopal", EmailAddress = "raja0@adventure-works.com", Phone = "1 (11) 500 555-0195"},
                new Customer { CustomerID = 343, Title = "Ms", FirstName = "Patricia", LastName = "Vasquez", EmailAddress = "patricia2@adventure-works.com", Phone = "490-555-0132"},
                new Customer { CustomerID = 344, Title = "Ms", FirstName = "Karren", LastName = "Burkhardt", EmailAddress = "karren0@adventure-works.com", Phone = "652-555-0132"},
                new Customer { CustomerID = 345, Title = "Ms", FirstName = "Abigail", LastName = "Gonzalez", EmailAddress = "abigail0@adventure-works.com", Phone = "121-555-0139"},
                new Customer { CustomerID = 346, Title = "Mr", FirstName = "Ranjit", LastName = "Varkey Chudukatil", EmailAddress = "ranjit1@adventure-works.com", Phone = "810-555-0160"},
                new Customer { CustomerID = 347, Title = "Ms", FirstName = "Ingrid", LastName = "Burkhardt", EmailAddress = "ingrid0@adventure-works.com", Phone = "857-555-0187"},
                new Customer { CustomerID = 348, Title = "Mr", FirstName = "Oscar", LastName = "Alpuerto", EmailAddress = "oscar0@adventure-works.com", Phone = "855-555-0174"},
                new Customer { CustomerID = 349, Title = "Mr", FirstName = "Gary", LastName = "Vargas", EmailAddress = "gary6@adventure-works.com", Phone = "112-555-0176"},
                new Customer { CustomerID = 352, Title = "Mr", FirstName = "Shane", LastName = "Kim", EmailAddress = "shane2@adventure-works.com", Phone = "155-555-0149"},
                new Customer { CustomerID = 353, Title = "Ms", FirstName = "Joan", LastName = "Campbell", EmailAddress = "joan0@adventure-works.com", Phone = "700-555-0155"},
                new Customer { CustomerID = 354, Title = "Mr", FirstName = "Maxwell", LastName = "Amland", EmailAddress = "maxwell0@adventure-works.com", Phone = "614-555-0134"},
                new Customer { CustomerID = 358, Title = "Mr", FirstName = "Joe", LastName = "Kim", EmailAddress = "joe1@adventure-works.com", Phone = "1 (11) 500 555-0144"},
                new Customer { CustomerID = 360, Title = "Ms", FirstName = "Ramona", LastName = "Antrim", EmailAddress = "ramona0@adventure-works.com", Phone = "327-555-0148"},
                new Customer { CustomerID = 361, Title = "Ms", FirstName = "Karan", LastName = "Khanna", EmailAddress = "karan1@adventure-works.com", Phone = "390-555-0150"},
                new Customer { CustomerID = 362, Title = "Ms", FirstName = "Sharon", LastName = "Crow", EmailAddress = "sharon1@adventure-works.com", Phone = "889-555-0176"},
                new Customer { CustomerID = 363, Title = "Mr", FirstName = "Chris", LastName = "Ashton", EmailAddress = "chris3@adventure-works.com", Phone = "556-555-0145"},
                new Customer { CustomerID = 364, Title = "Mr", FirstName = "Imtiaz", LastName = "Khan", EmailAddress = "imtiaz0@adventure-works.com", Phone = "249-555-0179"},
                new Customer { CustomerID = 365, Title = "Mr", FirstName = "Jack", LastName = "Creasey", EmailAddress = "jack2@adventure-works.com", Phone = "539-555-0182"},
                new Customer { CustomerID = 366, Title = "Ms", FirstName = "Teresa", LastName = "Atkinson", EmailAddress = "teresa0@adventure-works.com", Phone = "129-555-0110"},
                new Customer { CustomerID = 367, Title = "Ms", FirstName = "Tammy", LastName = "Khan", EmailAddress = "tammy0@adventure-works.com", Phone = "145-555-0166"},
                new Customer { CustomerID = 370, Title = "Ms", FirstName = "Elizabeth", LastName = "Keyser", EmailAddress = "elizabeth2@adventure-works.com", Phone = "656-555-0173"},
                new Customer { CustomerID = 371, Title = "Mr", FirstName = "Bruno", LastName = "Costa Da Silva", EmailAddress = "bruno0@adventure-works.com", Phone = "140-555-0143"},
                new Customer { CustomerID = 372, Title = "Ms", FirstName = "Katherine", LastName = "Swan", EmailAddress = "katherine1@adventure-works.com", Phone = "421-555-0192"},
                new Customer { CustomerID = 376, Title = "Ms", FirstName = "Mary", LastName = "Kesslep", EmailAddress = "mary8@adventure-works.com", Phone = "1 (11) 500 555-0146"},
                new Customer { CustomerID = 377, Title = "Mr", FirstName = "Marlin", LastName = "Coriell", EmailAddress = "marlin0@adventure-works.com", Phone = "941-555-0155"},
                new Customer { CustomerID = 379, Title = "Mr", FirstName = "Kevin", LastName = "Kennedy", EmailAddress = "kevin4@adventure-works.com", Phone = "275-555-0179"},
                new Customer { CustomerID = 380, Title = "Ms", FirstName = "Eva", LastName = "Corets", EmailAddress = "eva0@adventure-works.com", Phone = "542-555-0164"},
                new Customer { CustomerID = 381, Title = "Ms", FirstName = "Julie", LastName = "Taft-Rider", EmailAddress = "julie1@adventure-works.com", Phone = "145-555-0194"},
                new Customer { CustomerID = 382, Title = "Mr", FirstName = "Robert", LastName = "Kelly", EmailAddress = "robert7@adventure-works.com", Phone = "510-555-0123"},
                new Customer { CustomerID = 383, Title = "Mr", FirstName = "Scott", LastName = "Cooper", EmailAddress = "scott2@adventure-works.com", Phone = "773-555-0182"},
                new Customer { CustomerID = 384, Title = "Mr", FirstName = "Clarence", LastName = "Tatman", EmailAddress = "clarence0@adventure-works.com", Phone = "787-555-0128"},
                new Customer { CustomerID = 385, Title = "Mr", FirstName = "John", LastName = "Kelly", EmailAddress = "john22@adventure-works.com", Phone = "330-555-0116"},
                new Customer { CustomerID = 388, Title = "Mr", FirstName = "Victor", LastName = "Kelley", EmailAddress = "victor0@adventure-works.com", Phone = "112-555-0195"},
                new Customer { CustomerID = 389, Title = "Ms", FirstName = "Dorothy", LastName = "Contreras", EmailAddress = "dorothy0@adventure-works.com", Phone = "428-555-0176"},
                new Customer { CustomerID = 390, Title = "Mr", FirstName = "Mike", LastName = "Taylor", EmailAddress = "mike6@adventure-works.com", Phone = "204-555-0189"},
                new Customer { CustomerID = 394, Title = "Ms", FirstName = "Bonnie", LastName = "Kearney", EmailAddress = "bonnie1@adventure-works.com", Phone = "1 (11) 500 555-0116"},
                new Customer { CustomerID = 395, Title = "Ms", FirstName = "June", LastName = "Brunner", EmailAddress = "june0@adventure-works.com", Phone = "249-555-0172"},
                new Customer { CustomerID = 397, Title = "Mr", FirstName = "Sandeep", LastName = "Katyal", EmailAddress = "sandeep2@adventure-works.com", Phone = "928-555-0117"},
                new Customer { CustomerID = 398, Title = "Ms", FirstName = "Shirley", LastName = "Bruner", EmailAddress = "shirley0@adventure-works.com", Phone = "383-555-0155"},
                new Customer { CustomerID = 399, Title = "Mr", FirstName = "Chad", LastName = "Tedford", EmailAddress = "chad1@adventure-works.com", Phone = "588-555-0128"},
                new Customer { CustomerID = 400, Title = "Mr", FirstName = "Peter", LastName = "Houston", EmailAddress = "peter3@adventure-works.com", Phone = "632-555-0171"},
                new Customer { CustomerID = 401, Title = "Mr", FirstName = "Tom", LastName = "Johnston", EmailAddress = "tom1@adventure-works.com", Phone = "883-555-0177"},
                new Customer { CustomerID = 402, Title = "Ms", FirstName = "Marian", LastName = "Berch", EmailAddress = "marian0@adventure-works.com", Phone = "640-555-0198"},
                new Customer { CustomerID = 403, Title = "Ms", FirstName = "Juanita", LastName = "Holman", EmailAddress = "juanita0@adventure-works.com", Phone = "996-555-0196"},
                new Customer { CustomerID = 406, Title = "Mr", FirstName = "Eddie", LastName = "Holmes", EmailAddress = "eddie0@adventure-works.com", Phone = "570-555-0199"},
                new Customer { CustomerID = 407, Title = "Mr", FirstName = "Robert", LastName = "Avalos", EmailAddress = "robert2@adventure-works.com", Phone = "665-555-0198"},
                new Customer { CustomerID = 408, Title = "Mr", FirstName = "Alexander", LastName = "Berger", EmailAddress = "alexander0@adventure-works.com", Phone = "519-555-0151"},
                new Customer { CustomerID = 412, Title = "Ms", FirstName = "Jean", LastName = "Holloway", EmailAddress = "jean2@adventure-works.com", Phone = "1 (11) 500 555-0181"},
                new Customer { CustomerID = 415, Title = "Mr", FirstName = "Greg", LastName = "Chapman", EmailAddress = "greg1@adventure-works.com", Phone = "708-555-0169"},
                new Customer { CustomerID = 416, Title = "Ms", FirstName = "Angela", LastName = "Barbariol", EmailAddress = "angela1@adventure-works.com", Phone = "134-555-0182"},
                new Customer { CustomerID = 417, Title = "Ms", FirstName = "Ruth", LastName = "Choin", EmailAddress = "ruth1@adventure-works.com", Phone = "273-555-0181"},
                new Customer { CustomerID = 418, Title = "Mr", FirstName = "Lee", LastName = "Chapla", EmailAddress = "lee0@adventure-works.com", Phone = "223-555-0184"},
                new Customer { CustomerID = 419, Title = "Mr", FirstName = "Darrell", LastName = "Banks", EmailAddress = "darrell0@adventure-works.com", Phone = "816-555-0118"},
                new Customer { CustomerID = 420, Title = "Mr", FirstName = "Anthony", LastName = "Chor", EmailAddress = "anthony0@adventure-works.com", Phone = "429-555-0145"},
                new Customer { CustomerID = 421, Title = "Mr", FirstName = "Forrest", LastName = "Chandler", EmailAddress = "forrest0@adventure-works.com", Phone = "448-555-0179"},
                new Customer { CustomerID = 424, Title = "Mr", FirstName = "Eli", LastName = "Bowen", EmailAddress = "eli0@adventure-works.com", Phone = "371-555-0143"},
                new Customer { CustomerID = 425, Title = "Mr", FirstName = "Stephen", LastName = "Jiang", EmailAddress = "stephen3@adventure-works.com", Phone = "910-555-0116"},
                new Customer { CustomerID = 426, Title = "Mr", FirstName = "Dirk", LastName = "Bruno", EmailAddress = "dirk0@adventure-works.com", Phone = "817-555-0114"},
                new Customer { CustomerID = 430, Title = "Mr", FirstName = "Gustavo", LastName = "Camargo", EmailAddress = "gustavo1@adventure-works.com", Phone = "1 (11) 500 555-0118"},
                new Customer { CustomerID = 431, Title = "Mr", FirstName = "Douglas", LastName = "Baldwin", EmailAddress = "douglas1@adventure-works.com", Phone = "583-555-0130"},
                new Customer { CustomerID = 433, Title = "Ms", FirstName = "Lindsey", LastName = "Camacho", EmailAddress = "lindsey0@adventure-works.com", Phone = "827-555-0143"},
                new Customer { CustomerID = 434, Title = "Mr", FirstName = "James", LastName = "Bailey", EmailAddress = "james3@adventure-works.com", Phone = "234-555-0112"},
                new Customer { CustomerID = 435, Title = "Ms", FirstName = "Carol", LastName = "Elliott", EmailAddress = "carol2@adventure-works.com", Phone = "847-555-0151"},
                new Customer { CustomerID = 436, Title = "Ms", FirstName = "Barbara", LastName = "Calone", EmailAddress = "barbara2@adventure-works.com", Phone = "145-555-0152"},
                new Customer { CustomerID = 437, Title = "Ms", FirstName = "Megan", LastName = "Burke", EmailAddress = "megan0@adventure-works.com", Phone = "148-555-0149"},
                new Customer { CustomerID = 438, Title = "Mr", FirstName = "Cory", LastName = "Booth", EmailAddress = "cory0@adventure-works.com", Phone = "121-555-0157"},
                new Customer { CustomerID = 439, Title = "Ms", FirstName = "Shannon", LastName = "Elliott", EmailAddress = "shannon0@adventure-works.com", Phone = "425-555-0158"},
                new Customer { CustomerID = 442, Title = "Ms", FirstName = "Jauna", LastName = "Elson", EmailAddress = "jauna0@adventure-works.com", Phone = "185-555-0190"},
                new Customer { CustomerID = 443, Title = "Mrs", FirstName = "Janaina Barreiro Gambaro", LastName = "Bueno", EmailAddress = "janainabarreirogambaro0@adventure-works.com", Phone = "476-555-0184"},
                new Customer { CustomerID = 444, Title = "Mr", FirstName = "Shaun", LastName = "Beasley", EmailAddress = "shaun0@adventure-works.com", Phone = "396-555-0187"},
                new Customer { CustomerID = 448, Title = "Mr", FirstName = "Terry", LastName = "Eminhizer", EmailAddress = "terry1@adventure-works.com", Phone = "1 (11) 500 555-0176"},
                new Customer { CustomerID = 451, Title = "Mr", FirstName = "John", LastName = "Emory", EmailAddress = "john16@adventure-works.com", Phone = "691-555-0149"},
                new Customer { CustomerID = 452, Title = "Ms", FirstName = "Olga", LastName = "Trau", EmailAddress = "olga0@adventure-works.com", Phone = "398-555-0167"},
                new Customer { CustomerID = 453, Title = "Mr", FirstName = "Jon", LastName = "Ganio", EmailAddress = "jon0@adventure-works.com", Phone = "672-555-0112"},
                new Customer { CustomerID = 454, Title = "Ms", FirstName = "Gail", LastName = "Erickson", EmailAddress = "gail1@adventure-works.com", Phone = "834-555-0132"},
                new Customer { CustomerID = 455, Title = "Mr", FirstName = "James", LastName = "Tran", EmailAddress = "james15@adventure-works.com", Phone = "740-555-0159"},
                new Customer { CustomerID = 456, Title = "Mr", FirstName = "Michael", LastName = "Galos", EmailAddress = "michael15@adventure-works.com", Phone = "912-555-0149"},
                new Customer { CustomerID = 457, Title = "Mr", FirstName = "Mark", LastName = "Erickson", EmailAddress = "mark2@adventure-works.com", Phone = "962-555-0112"},
                new Customer { CustomerID = 460, Title = "Ms", FirstName = "Martha", LastName = "Espinoza", EmailAddress = "martha0@adventure-works.com", Phone = "753-555-0179"},
                new Customer { CustomerID = 461, Title = "Mr", FirstName = "Glenn", LastName = "Track", EmailAddress = "glenn0@adventure-works.com", Phone = "907-555-0170"},
                new Customer { CustomerID = 462, Title = "Mr", FirstName = "Bob", LastName = "Gage", EmailAddress = "bob1@adventure-works.com", Phone = "962-555-0175"},
                new Customer { CustomerID = 466, Title = "Mrs", FirstName = "Janeth", LastName = "Esteves", EmailAddress = "janeth1@adventure-works.com", Phone = "1 (11) 500 555-0136"},
                new Customer { CustomerID = 468, Title = "Mr", FirstName = "Paul", LastName = "Fulton", EmailAddress = "paul3@adventure-works.com", Phone = "492-555-0146"},
                new Customer { CustomerID = 469, Title = "Ms", FirstName = "Twanna", LastName = "Evans", EmailAddress = "twanna0@adventure-works.com", Phone = "554-555-0124"},
                new Customer { CustomerID = 470, Title = "Ms", FirstName = "Delia", LastName = "Toone", EmailAddress = "delia0@adventure-works.com", Phone = "328-555-0192"},
                new Customer { CustomerID = 471, Title = "Mr", FirstName = "John", LastName = "Ford", EmailAddress = "john19@adventure-works.com", Phone = "596-555-0153"},
                new Customer { CustomerID = 472, Title = "Ms", FirstName = "Ann", LastName = "Evans", EmailAddress = "ann1@adventure-works.com", Phone = "252-555-0127"},
                new Customer { CustomerID = 473, Title = "Ms", FirstName = "Kay", LastName = "Krane", EmailAddress = "kay0@adventure-works.com", Phone = "731-555-0187"},
                new Customer { CustomerID = 474, Title = "Mr", FirstName = "Mihail", LastName = "Frintu", EmailAddress = "mihail1@adventure-works.com", Phone = "777-555-0163"},
                new Customer { CustomerID = 475, Title = "Mr", FirstName = "John", LastName = "Evans", EmailAddress = "john17@adventure-works.com", Phone = "581-555-0172"},
                new Customer { CustomerID = 478, Title = "Ms", FirstName = "Ruby Sue", LastName = "Styles", EmailAddress = "rubysue0@adventure-works.com", Phone = "512-555-0122"},
                new Customer { CustomerID = 479, Title = "Ms", FirstName = "Lori", LastName = "Kane", EmailAddress = "lori2@adventure-works.com", Phone = "765-555-0141"},
                new Customer { CustomerID = 480, Title = "Ms", FirstName = "Susan", LastName = "French", EmailAddress = "susan3@adventure-works.com", Phone = "994-555-0194"},
                new Customer { CustomerID = 484, Title = "Mr", FirstName = "Gary", LastName = "Suess", EmailAddress = "gary5@adventure-works.com", Phone = "1 (11) 500 555-0199"},
                new Customer { CustomerID = 487, Title = "Ms", FirstName = "Ruth", LastName = "Suffin", EmailAddress = "ruth2@adventure-works.com", Phone = "924-555-0195"},
                new Customer { CustomerID = 488, Title = "Ms", FirstName = "Margaret", LastName = "Smith", EmailAddress = "margaret0@adventure-works.com", Phone = "959-555-0151"},
                new Customer { CustomerID = 489, Title = "Ms", FirstName = "Dorothy", LastName = "Fox", EmailAddress = "dorothy1@adventure-works.com", Phone = "191-555-0198"},
                new Customer { CustomerID = 490, Title = "Ms", FirstName = "Elizabeth", LastName = "Sullivan", EmailAddress = "elizabeth4@adventure-works.com", Phone = "306-555-0112"},
                new Customer { CustomerID = 491, Title = "Ms", FirstName = "Frances", LastName = "Adams", EmailAddress = "frances0@adventure-works.com", Phone = "991-555-0183"},
                new Customer { CustomerID = 492, Title = "Mr", FirstName = "Garth", LastName = "Fort", EmailAddress = "garth0@adventure-works.com", Phone = "768-555-0125"},
                new Customer { CustomerID = 493, Title = "Mr", FirstName = "Michael", LastName = "Sullivan", EmailAddress = "michael24@adventure-works.com", Phone = "323-555-0113"},
                new Customer { CustomerID = 496, Title = "Ms", FirstName = "Marcia", LastName = "Sultan", EmailAddress = "marcia0@adventure-works.com", Phone = "613-555-0116"},
                new Customer { CustomerID = 497, Title = "Ms", FirstName = "Amy", LastName = "Alberts", EmailAddress = "amy1@adventure-works.com", Phone = "727-555-0115"},
                new Customer { CustomerID = 498, Title = "Ms", FirstName = "Kelly", LastName = "Focht", EmailAddress = "kelly0@adventure-works.com", Phone = "272-555-0123"},
                new Customer { CustomerID = 502, Title = "Mr", FirstName = "Krishna", LastName = "Sunkammurali", EmailAddress = "krishna1@adventure-works.com", Phone = "1 (11) 500 555-0177"},
                new Customer { CustomerID = 504, Title = "Ms", FirstName = "Mae", LastName = "Black", EmailAddress = "mae1@adventure-works.com", Phone = "264-555-0143"},
                new Customer { CustomerID = 505, Title = "Mr", FirstName = "Brad", LastName = "Sutton", EmailAddress = "brad0@adventure-works.com", Phone = "688-555-0115"},
                new Customer { CustomerID = 506, Title = "Mr", FirstName = "François", LastName = "Ferrier", EmailAddress = "françois1@adventure-works.com", Phone = "571-555-0128"},
                new Customer { CustomerID = 507, Title = "Mr", FirstName = "Mary", LastName = "Bishop", EmailAddress = "mary4@adventure-works.com", Phone = "176-555-0136"},
                new Customer { CustomerID = 508, Title = "Mr", FirstName = "Martin", LastName = "Svoboda", EmailAddress = "martin1@adventure-works.com", Phone = "132-555-0149"},
                new Customer { CustomerID = 509, Title = "Mr", FirstName = "Robert", LastName = "Ahlering", EmailAddress = "robert1@adventure-works.com", Phone = "678-555-0175"},
                new Customer { CustomerID = 510, Title = "Mr", FirstName = "Jimmy", LastName = "Bischoff", EmailAddress = "jimmy1@adventure-works.com", Phone = "992-555-0111"},
                new Customer { CustomerID = 511, Title = "Mr", FirstName = "Abraham", LastName = "Swearengin", EmailAddress = "abraham0@adventure-works.com", Phone = "926-555-0136"},
                new Customer { CustomerID = 514, Title = "Mr", FirstName = "Ryan", LastName = "Calafato", EmailAddress = "ryan1@adventure-works.com", Phone = "726-555-0155"},
                new Customer { CustomerID = 515, Title = "Mr", FirstName = "Dragan", LastName = "Tomic", EmailAddress = "dragan1@adventure-works.com", Phone = "833-555-0167"},
                new Customer { CustomerID = 516, Title = "Mr", FirstName = "Thomas", LastName = "Michaels", EmailAddress = "thomas2@adventure-works.com", Phone = "162-555-0174"},
                new Customer { CustomerID = 520, Title = "Ms", FirstName = "Mari", LastName = "Caldwell", EmailAddress = "mari0@adventure-works.com", Phone = "1 (11) 500 555-0118"},
                new Customer { CustomerID = 523, Title = "Ms", FirstName = "Mary", LastName = "Gimmi", EmailAddress = "mary6@adventure-works.com", Phone = "149-555-0196"},
                new Customer { CustomerID = 526, Title = "Mr", FirstName = "David", LastName = "Givens", EmailAddress = "david15@adventure-works.com", Phone = "605-555-0111"},
                new Customer { CustomerID = 527, Title = "Ms", FirstName = "Diane", LastName = "Tibbott", EmailAddress = "diane5@adventure-works.com", Phone = "847-555-0184"},
                new Customer { CustomerID = 528, Title = "Ms", FirstName = "Helen", LastName = "Meyer", EmailAddress = "helen2@adventure-works.com", Phone = "519-555-0112"},
                new Customer { CustomerID = 529, Title = "Ms", FirstName = "Jeanie", LastName = "Glenn", EmailAddress = "jeanie0@adventure-works.com", Phone = "669-555-0149"},
                new Customer { CustomerID = 532, Title = "Ms", FirstName = "Diane", LastName = "Glimp", EmailAddress = "diane3@adventure-works.com", Phone = "898-555-0137"},
                new Customer { CustomerID = 533, Title = "Ms", FirstName = "Yuping", LastName = "Tian", EmailAddress = "yuping0@adventure-works.com", Phone = "744-555-0123"},
                new Customer { CustomerID = 534, Title = "Mr", FirstName = "Stephen", LastName = "Mew", EmailAddress = "stephen4@adventure-works.com", Phone = "399-555-0114"},
                new Customer { CustomerID = 538, Title = "Mr", FirstName = "John", LastName = "Brooks", EmailAddress = "john12@adventure-works.com", Phone = "1 (11) 500 555-0179"},
                new Customer { CustomerID = 541, Title = "Mr", FirstName = "Willie", LastName = "Brooks", EmailAddress = "willie0@adventure-works.com", Phone = "525-555-0174"},
                new Customer { CustomerID = 542, Title = "Mr", FirstName = "Andrew", LastName = "Kobylinski", EmailAddress = "andrew5@adventure-works.com", Phone = "129-555-0185"},
                new Customer { CustomerID = 543, Title = "Mr", FirstName = "R. Morgan", LastName = "Mendoza", EmailAddress = "rmorgan0@adventure-works.com", Phone = "963-555-0146"},
                new Customer { CustomerID = 544, Title = "Mr", FirstName = "Jay", LastName = "Adams", EmailAddress = "jay1@adventure-works.com", Phone = "158-555-0142"},
                new Customer { CustomerID = 545, Title = "Mr", FirstName = "Christian", LastName = "Kleinerman", EmailAddress = "christian1@adventure-works.com", Phone = "362-555-0177"},
                new Customer { CustomerID = 546, Title = "Mr", FirstName = "Anton", LastName = "Kirilov", EmailAddress = "anton0@adventure-works.com", Phone = "608-555-0162"},
                new Customer { CustomerID = 547, Title = "Ms", FirstName = "Gladys", LastName = "Mendiola", EmailAddress = "gladys0@adventure-works.com", Phone = "535-555-0189"},
                new Customer { CustomerID = 550, Title = "Ms", FirstName = "Raquel", LastName = "Mello", EmailAddress = "raquel0@adventure-works.com", Phone = "723-555-0124"},
                new Customer { CustomerID = 551, Title = "Mr", FirstName = "Samuel", LastName = "Agcaoili", EmailAddress = "samuel0@adventure-works.com", Phone = "554-555-0110"},
                new Customer { CustomerID = 552, Title = "Mr", FirstName = "Tim", LastName = "Kim", EmailAddress = "tim0@adventure-works.com", Phone = "244-555-0115"},
                new Customer { CustomerID = 556, Title = "Ms", FirstName = "Nancy", LastName = "McPhearson", EmailAddress = "nancy3@adventure-works.com", Phone = "1 (11) 500 555-0195"},
                new Customer { CustomerID = 559, Title = "Ms", FirstName = "Nkenge", LastName = "McLin", EmailAddress = "nkenge0@adventure-works.com", Phone = "158-555-0123"},
                new Customer { CustomerID = 560, Title = "Mr", FirstName = "Paul", LastName = "Alcorn", EmailAddress = "paul2@adventure-works.com", Phone = "331-555-0162"},
                new Customer { CustomerID = 561, Title = "Mr", FirstName = "Marvin", LastName = "Allen", EmailAddress = "marvin0@adventure-works.com", Phone = "447-555-0110"},
                new Customer { CustomerID = 562, Title = "Ms", FirstName = "Yvonne", LastName = "McKay", EmailAddress = "yvonne1@adventure-works.com", Phone = "623-555-0144"},
                new Customer { CustomerID = 563, Title = "Mr", FirstName = "Sean", LastName = "Jacobson", EmailAddress = "sean2@adventure-works.com", Phone = "555-555-0162"},
                new Customer { CustomerID = 564, Title = "Ms", FirstName = "Michelle", LastName = "Alexander", EmailAddress = "michelle0@adventure-works.com", Phone = "115-555-0175"},
                new Customer { CustomerID = 565, Title = "Mr", FirstName = "Richard", LastName = "Bentley", EmailAddress = "richard0@adventure-works.com", Phone = "911-555-0153"},
                new Customer { CustomerID = 568, Title = "Mr", FirstName = "Curtis", LastName = "Howard", EmailAddress = "curtis0@adventure-works.com", Phone = "555-555-0162"},
                new Customer { CustomerID = 569, Title = "Mr", FirstName = "Cecil", LastName = "Allison", EmailAddress = "cecil0@adventure-works.com", Phone = "699-555-0155"},
                new Customer { CustomerID = 570, Title = "Mr", FirstName = "Gregory", LastName = "Alderson", EmailAddress = "gregory0@adventure-works.com", Phone = "968-555-0153"},
                new Customer { CustomerID = 574, Title = "Ms", FirstName = "Janice", LastName = "Hows", EmailAddress = "janice1@adventure-works.com", Phone = "1 (11) 500 555-0119"},
                new Customer { CustomerID = 577, Title = "Mr", FirstName = "George", LastName = "Huckaby", EmailAddress = "george1@adventure-works.com", Phone = "851-555-0127"},
                new Customer { CustomerID = 578, Title = "Ms", FirstName = "Carolyn", LastName = "Farino", EmailAddress = "carolyn0@adventure-works.com", Phone = "957-555-0125"},
                new Customer { CustomerID = 579, Title = "Ms", FirstName = "Kim", LastName = "Abercrombie", EmailAddress = "kim2@adventure-works.com", Phone = "334-555-0137"},
                new Customer { CustomerID = 580, Title = "Mr", FirstName = "Joshua", LastName = "Huff", EmailAddress = "joshua0@adventure-works.com", Phone = "190-555-0186"},
                new Customer { CustomerID = 581, Title = "Ms", FirstName = "Geri", LastName = "Farrell", EmailAddress = "geri0@adventure-works.com", Phone = "329-555-0183"},
                new Customer { CustomerID = 582, Title = "Ms", FirstName = "Catherine", LastName = "Abel", EmailAddress = "catherine0@adventure-works.com", Phone = "747-555-0171"},
                new Customer { CustomerID = 583, Title = "Ms", FirstName = "Laura", LastName = "Steele", EmailAddress = "laura3@adventure-works.com", Phone = "741-555-0173"},
                new Customer { CustomerID = 586, Title = "Ms", FirstName = "Shanay", LastName = "Steelman", EmailAddress = "shanay0@adventure-works.com", Phone = "797-555-0118"},
                new Customer { CustomerID = 587, Title = "Ms", FirstName = "Rhoda", LastName = "Finley", EmailAddress = "rhoda0@adventure-works.com", Phone = "920-555-0191"},
                new Customer { CustomerID = 588, Title = "Mr", FirstName = "Pat", LastName = "Chambers", EmailAddress = "pat1@adventure-works.com", Phone = "127-555-0124"},
                new Customer { CustomerID = 592, Title = "Mr", FirstName = "Stefano", LastName = "Stefani", EmailAddress = "stefano0@adventure-works.com", Phone = "1 (11) 500 555-0115"},
                new Customer { CustomerID = 595, Title = "Mr", FirstName = "Alan", LastName = "Steiner", EmailAddress = "alan4@adventure-works.com", Phone = "792-555-0194"},
                new Customer { CustomerID = 596, Title = "Ms", FirstName = "Kathie", LastName = "Flood", EmailAddress = "kathie1@adventure-works.com", Phone = "627-555-0192"},
                new Customer { CustomerID = 597, Title = "Mr", FirstName = "Bob", LastName = "Hodges", EmailAddress = "bob2@adventure-works.com", Phone = "129-555-0120"},
                new Customer { CustomerID = 598, Title = "Mr", FirstName = "Derik", LastName = "Stenerson", EmailAddress = "derik0@adventure-works.com", Phone = "441-555-0144"},
                new Customer { CustomerID = 599, Title = "Mr", FirstName = "Raul", LastName = "Casts", EmailAddress = "raul0@adventure-works.com", Phone = "362-555-0162"},
                new Customer { CustomerID = 600, Title = "Ms", FirstName = "Holly", LastName = "Holt", EmailAddress = "holly1@adventure-works.com", Phone = "654-555-0150"},
                new Customer { CustomerID = 601, Title = "Mr", FirstName = "Vassar", LastName = "Stern", EmailAddress = "vassar0@adventure-works.com", Phone = "328-555-0123"},
                new Customer { CustomerID = 604, Title = "Ms", FirstName = "Wathalee", LastName = "Steuber", EmailAddress = "wathalee0@adventure-works.com", Phone = "517-555-0120"},
                new Customer { CustomerID = 605, Title = "Mr", FirstName = "Matthew", LastName = "Cavallari", EmailAddress = "matthew1@adventure-works.com", Phone = "695-555-0161"},
                new Customer { CustomerID = 606, Title = "Ms", FirstName = "Helge", LastName = "Hoeing", EmailAddress = "helge0@adventure-works.com", Phone = "850-555-0198"},
                new Customer { CustomerID = 607, Title = "Ms", FirstName = "Alice", LastName = "Steiner", EmailAddress = "alice4@adventure-works.com", Phone = "355-555-0180"},
                new Customer { CustomerID = 608, Title = "Mr", FirstName = "Steven", LastName = "Brown", EmailAddress = "steven1@adventure-works.com", Phone = "280-555-0124"},
                new Customer { CustomerID = 609, Title = "Mr", FirstName = "David", LastName = "Hodgson", EmailAddress = "david16@adventure-works.com", Phone = "969-555-0117"},
                new Customer { CustomerID = 610, Title = "Ms", FirstName = "Liza Marie", LastName = "Stevens", EmailAddress = "lizamarie0@adventure-works.com", Phone = "366-555-0110"},
                new Customer { CustomerID = 613, Title = "Mr", FirstName = "Jim", LastName = "Stewart", EmailAddress = "jim5@adventure-works.com", Phone = "226-555-0110"},
                new Customer { CustomerID = 617, Title = "Ms", FirstName = "Arlene", LastName = "Huff", EmailAddress = "arlene0@adventure-works.com", Phone = "1 (11) 500 555-0146"},
                new Customer { CustomerID = 620, Title = "Mr", FirstName = "Matthew", LastName = "Hunter", EmailAddress = "matthew4@adventure-works.com", Phone = "482-555-0188"},
                new Customer { CustomerID = 621, Title = "Mr", FirstName = "Matthew", LastName = "Hink", EmailAddress = "matthew3@adventure-works.com", Phone = "146-555-0176"},
                new Customer { CustomerID = 622, Title = "Mr", FirstName = "Robert", LastName = "Stotka", EmailAddress = "robert12@adventure-works.com", Phone = "493-555-0185"},
                new Customer { CustomerID = 623, Title = "Ms", FirstName = "Phyllis", LastName = "Huntsman", EmailAddress = "phyllis1@adventure-works.com", Phone = "153-555-0195"},
                new Customer { CustomerID = 624, Title = "Mr", FirstName = "Mike", LastName = "Hines", EmailAddress = "mike3@adventure-works.com", Phone = "454-555-0160"},
                new Customer { CustomerID = 625, Title = "Ms", FirstName = "Kayla", LastName = "Stotler", EmailAddress = "kayla0@adventure-works.com", Phone = "315-555-0131"},
                new Customer { CustomerID = 626, Title = "Mr", FirstName = "Lawrence", LastName = "Hurkett", EmailAddress = "lawrence0@adventure-works.com", Phone = "129-555-0185"},
                new Customer { CustomerID = 629, Title = "Mr", FirstName = "Ryan", LastName = "Ihrig", EmailAddress = "ryan4@adventure-works.com", Phone = "809-555-0152"},
                new Customer { CustomerID = 630, Title = "Mr", FirstName = "Andrew", LastName = "Hill", EmailAddress = "andrew4@adventure-works.com", Phone = "194-555-0149"},
                new Customer { CustomerID = 631, Title = "Mr", FirstName = "Robert", LastName = "Lyeba", EmailAddress = "robert8@adventure-works.com", Phone = "631-555-0155"},
                new Customer { CustomerID = 635, Title = "Mr", FirstName = "Roger", LastName = "Van Houten", EmailAddress = "roger2@adventure-works.com", Phone = "1 (11) 500 555-0110"},
                new Customer { CustomerID = 637, Title = "Mr", FirstName = "Robert", LastName = "Lyon", EmailAddress = "robert9@adventure-works.com", Phone = "666-555-0143"},
                new Customer { CustomerID = 641, Title = "Ms", FirstName = "Rose", LastName = "Vandenouer", EmailAddress = "rose1@adventure-works.com", Phone = "1 (11) 500 555-0140"},
                new Customer { CustomerID = 643, Title = "Ms", FirstName = "Denise", LastName = "Maccietto", EmailAddress = "denise1@adventure-works.com", Phone = "537-555-0190"},
                new Customer { CustomerID = 644, Title = "Mr", FirstName = "Gregory", LastName = "Vanderbout", EmailAddress = "gregory1@adventure-works.com", Phone = "684-555-0134"},
                new Customer { CustomerID = 645, Title = "Mr", FirstName = "Ronald", LastName = "Heymsfield", EmailAddress = "ronald1@adventure-works.com", Phone = "784-555-0120"},
                new Customer { CustomerID = 646, Title = "Mr", FirstName = "Scott", LastName = "MacDonald", EmailAddress = "scott7@adventure-works.com", Phone = "470-555-0171"},
                new Customer { CustomerID = 647, Title = "Mr", FirstName = "Michael", LastName = "Vanderhyde", EmailAddress = "michael25@adventure-works.com", Phone = "918-555-0141"},
                new Customer { CustomerID = 648, Title = "Ms", FirstName = "Cheryl", LastName = "Herring", EmailAddress = "cheryl0@adventure-works.com", Phone = "158-555-0154"},
                new Customer { CustomerID = 649, Title = "Mr", FirstName = "Walter", LastName = "Mays", EmailAddress = "walter1@adventure-works.com", Phone = "245-555-0191"},
                new Customer { CustomerID = 650, Title = "Ms", FirstName = "Margaret", LastName = "Vanderkamp", EmailAddress = "margaret2@adventure-works.com", Phone = "265-555-0143"},
                new Customer { CustomerID = 653, Title = "Ms", FirstName = "Kara", LastName = "Vanderlinden", EmailAddress = "kara0@adventure-works.com", Phone = "680-555-0160"},
                new Customer { CustomerID = 654, Title = "Mr", FirstName = "Jésus", LastName = "Hernandez", EmailAddress = "jésus0@adventure-works.com", Phone = "214-555-0145"},
                new Customer { CustomerID = 655, Title = "Ms", FirstName = "Irene", LastName = "Hernandez", EmailAddress = "irene0@adventure-works.com", Phone = "790-555-0197"},
                new Customer { CustomerID = 659, Title = "Mr", FirstName = "Ajay", LastName = "Manchepalli", EmailAddress = "ajay0@adventure-works.com", Phone = "1 (11) 500 555-0174"},
                new Customer { CustomerID = 660, Title = "Mr", FirstName = "Nieves", LastName = "Vargas", EmailAddress = "nieves0@adventure-works.com", Phone = "371-555-0184"},
                new Customer { CustomerID = 661, Title = "Mr", FirstName = "Kari", LastName = "Hensien", EmailAddress = "kari0@adventure-works.com", Phone = "143-555-0129"},
                new Customer { CustomerID = 665, Title = "Mr", FirstName = "Tomas", LastName = "Manzanares", EmailAddress = "tomas0@adventure-works.com", Phone = "1 (11) 500 555-0178"},
                new Customer { CustomerID = 668, Title = "Ms", FirstName = "Kathy", LastName = "Marcovecchio", EmailAddress = "kathy0@adventure-works.com", Phone = "942-555-0141"},
                new Customer { CustomerID = 669, Title = "Ms", FirstName = "Patricia", LastName = "Doyle", EmailAddress = "patricia0@adventure-works.com", Phone = "899-555-0134"},
                new Customer { CustomerID = 670, Title = "Ms", FirstName = "Valerie", LastName = "Hendricks", EmailAddress = "valerie0@adventure-works.com", Phone = "859-555-0140"},
                new Customer { CustomerID = 671, Title = "Ms", FirstName = "Jill", LastName = "Markwood", EmailAddress = "jill2@adventure-works.com", Phone = "747-555-0113"},
                new Customer { CustomerID = 672, Title = "Mr", FirstName = "Gerald", LastName = "Drury", EmailAddress = "gerald0@adventure-works.com", Phone = "169-555-0178"},
                new Customer { CustomerID = 673, Title = "Mr", FirstName = "John", LastName = "Hanson", EmailAddress = "john20@adventure-works.com", Phone = "107-555-0117"},
                new Customer { CustomerID = 674, Title = "Ms", FirstName = "Melissa", LastName = "Marple", EmailAddress = "melissa0@adventure-works.com", Phone = "685-555-0117"},
                new Customer { CustomerID = 677, Title = "Ms", FirstName = "Cecelia", LastName = "Marshall", EmailAddress = "cecelia0@adventure-works.com", Phone = "394-555-0168"},
                new Customer { CustomerID = 678, Title = "Mr", FirstName = "Reuben", LastName = "D'sa", EmailAddress = "reuben1@adventure-works.com", Phone = "916-555-0137"},
                new Customer { CustomerID = 679, Title = "Ms", FirstName = "Brenda", LastName = "Heaney", EmailAddress = "brenda3@adventure-works.com", Phone = "393-555-0167"},
                new Customer { CustomerID = 683, Title = "Ms", FirstName = "Linda", LastName = "Martin", EmailAddress = "linda8@adventure-works.com", Phone = "1 (11) 500 555-0137"},
                new Customer { CustomerID = 685, Title = "Mr", FirstName = "James", LastName = "Haugh", EmailAddress = "james8@adventure-works.com", Phone = "763-555-0120"},
                new Customer { CustomerID = 689, Title = "Ms", FirstName = "Sandra", LastName = "Martinez", EmailAddress = "sandra3@adventure-works.com", Phone = "1 (11) 500 555-0113"},
                new Customer { CustomerID = 692, Title = "Ms", FirstName = "Bev", LastName = "Desalvo", EmailAddress = "bev0@adventure-works.com", Phone = "143-555-0113"},
                new Customer { CustomerID = 693, Title = "Mr", FirstName = "Bart", LastName = "Duncan", EmailAddress = "bart0@adventure-works.com", Phone = "539-555-0121"},
                new Customer { CustomerID = 694, Title = "Ms", FirstName = "Ann", LastName = "Hass", EmailAddress = "ann2@adventure-works.com", Phone = "713-555-0168"},
                new Customer { CustomerID = 695, Title = "Mr", FirstName = "Rob", LastName = "Caron", EmailAddress = "rob2@adventure-works.com", Phone = "620-555-0117"},
                new Customer { CustomerID = 696, Title = "Mr", FirstName = "Maciej", LastName = "Dusza", EmailAddress = "maciej1@adventure-works.com", Phone = "962-555-0144"},
                new Customer { CustomerID = 697, Title = "Mr", FirstName = "Roger", LastName = "Harui", EmailAddress = "roger0@adventure-works.com", Phone = "774-555-0133"},
                new Customer { CustomerID = 698, Title = "Mr", FirstName = "Andy", LastName = "Carothers", EmailAddress = "andy1@adventure-works.com", Phone = "944-555-0148"},
                new Customer { CustomerID = 701, Title = "Ms", FirstName = "Linda", LastName = "Ecoffey", EmailAddress = "linda5@adventure-works.com", Phone = "674-555-0188"}
            };
    }
}
